package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		log.Fatal(err)
	}
	modulePath := readModulePath(moduleRoot)

	buildersByPkg := make(map[string][]builderInfo)

	err = filepath.Walk(moduleRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			name := info.Name()
			if name == "vendor" || name == ".git" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		if strings.HasSuffix(path, "_gen.go") {
			return nil
		}
		if strings.Contains(path, "cmd"+string(filepath.Separator)) {
			return nil
		}

		relDir, _ := filepath.Rel(moduleRoot, filepath.Dir(path))
		pkgPath := filepath.ToSlash(relDir)

		// core 包内的 TaskStepBuilderFunc 是工具类型, 需要运行时配置, 不适合自动注册
		if pkgPath == "core" {
			return nil
		}

		builders, err := scanFile(path)
		if err != nil {
			return fmt.Errorf("scanning %s: %w", path, err)
		}
		if len(builders) > 0 {
			for i := range builders {
				builders[i].pkgPath = pkgPath
				builders[i].fqn = modulePath + "/" + pkgPath + "." + builders[i].structName
				if pkgPath == "." {
					builders[i].fqn = modulePath + "." + builders[i].structName
				}
			}
			buildersByPkg[pkgPath] = append(buildersByPkg[pkgPath], builders...)
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	for pkgPath, builders := range buildersByPkg {
		dir := filepath.Join(moduleRoot, filepath.FromSlash(pkgPath))
		if err := generateRegistration(dir, pkgPath, modulePath, builders); err != nil {
			log.Fatal(err)
		}
	}

	total := 0
	for _, bs := range buildersByPkg {
		total += len(bs)
	}
	fmt.Printf("register-gen: registered %d TaskStepBuilder(s) across %d package(s)\n", total, len(buildersByPkg))
	for _, builders := range buildersByPkg {
		for _, b := range builders {
			fmt.Printf("  %s\n", b.fqn)
		}
	}
}

type builderInfo struct {
	structName string
	pkgPath    string
	fqn        string
}

var (
	reStruct    = regexp.MustCompile(`^type\s+(\w+)\s+struct\s*\{`)
	reTitle     = regexp.MustCompile(`^func\s+\(\w+\s+\*(\w+)\)\s+TaskStepTitle\s*\(\s*\)\s+string\s*\{`)
	reBuildRecv = regexp.MustCompile(`^func\s+\(\w+\s+\*?(\w+)\)\s+Build\s*\(`)
)

func scanFile(path string) ([]builderInfo, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var structNames []string
	buildMethods := make(map[string]bool)
	titleMethods := make(map[string]bool)

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if m := reStruct.FindStringSubmatch(line); m != nil {
			structNames = append(structNames, m[1])
		}
		if m := reBuildRecv.FindStringSubmatch(line); m != nil {
			buildMethods[m[1]] = true
		}
		if m := reTitle.FindStringSubmatch(line); m != nil {
			titleMethods[m[1]] = true
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	var builders []builderInfo
	for _, name := range structNames {
		if buildMethods[name] && titleMethods[name] {
			builders = append(builders, builderInfo{structName: name})
		}
	}
	return builders, nil
}

func generateRegistration(dir, pkgPath, modulePath string, builders []builderInfo) error {
	sort.Slice(builders, func(i, j int) bool {
		return builders[i].structName < builders[j].structName
	})

	var b strings.Builder
	b.WriteString("// Code generated by register-gen; DO NOT EDIT.\n\n")
	b.WriteString("package " + filepath.Base(dir) + "\n\n")
	b.WriteString("import \"github.com/open-hzbank/ultra-flow/core\"\n\n")
	b.WriteString("func init() {\n")
	for _, bld := range builders {
		b.WriteString(fmt.Sprintf("\tcore.RegisterTaskStepBuilder(%q, &%s{})\n", bld.fqn, bld.structName))
	}
	b.WriteString("}\n")

	outPath := filepath.Join(dir, "builder_registry_gen.go")
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func readModulePath(root string) string {
	f, err := os.Open(filepath.Join(root, "go.mod"))
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module"))
		}
	}
	log.Fatal("module path not found in go.mod")
	return ""
}
