// Code generated by register-gen; DO NOT EDIT.

package unified

import "hzbank.com.cn/ultra-flow/core"

func init() {
	core.RegisterTaskStepBuilder("hzbank.com.cn/ultra-flow/scenes/unified/steps.TrafficRulePublishStepBuilder", &TrafficRulePublishStepBuilder{})
}
