// Code generated by register-gen; DO NOT EDIT.

package unified

import "github.com/open-hzbank/ultra-flow/core"

func init() {
	core.RegisterTaskStepBuilder("github.com/open-hzbank/ultra-flow/scenes/unified.TrafficRulePublishStepBuilder", &TrafficRulePublishStepBuilder{})
}
