// Code generated by register-gen; DO NOT EDIT.

package padding

import "hzbank.com.cn/ultra-flow/core"

func init() {
	core.RegisterTaskStepBuilder("hzbank.com.cn/ultra-flow/padding.FixedStatusTaskBuilder", &FixedStatusTaskBuilder{})
	core.RegisterTaskStepBuilder("hzbank.com.cn/ultra-flow/padding.NoneTaskStepBuilder", &NoneTaskStepBuilder{})
}
