// Code generated by register-gen; DO NOT EDIT.

package padding

import "github.com/open-hzbank/ultra-flow/core"

func init() {
	core.RegisterTaskStepBuilder("github.com/open-hzbank/ultra-flow/padding.FixedStatusTaskBuilder", &FixedStatusTaskBuilder{})
	core.RegisterTaskStepBuilder("github.com/open-hzbank/ultra-flow/padding.NoneTaskStepBuilder", &NoneTaskStepBuilder{})
}
